var g=Object.defineProperty;var i=(t,r)=>g(t,"name",{value:r,configurable:!0});let activeRDC=[];document.addEventListener("DOMContentLoaded",()=>{const t=document.querySelector("main");function r(){requestAnimationFrame(()=>t.classList.add("loaded"))}i(r,"markLoaded");try{const e=sessionStorage.getItem("rtl_studio_state_v1");if(e){const c=JSON.parse(e);c.selectedTopModule?document.getElementById("meta-top").textContent=c.selectedTopModule:c.graphData&&c.graphData.top_module&&(document.getElementById("meta-top").textContent=c.graphData.top_module)}}catch{}const a=sessionStorage.getItem("rtl_studio_rdc");if(!a){r();return}try{activeRDC=JSON.parse(a)}catch{activeRDC=[]}if(!Array.isArray(activeRDC)||activeRDC.length===0){r();return}const n=activeRDC.filter(e=>e.type==="rdc_unsync").length,s=activeRDC.filter(e=>e.type==="rdc_sync").length,o=new Set;activeRDC.forEach(e=>{e.launch_reset&&o.add(e.launch_reset),e.capture_reset&&o.add(e.capture_reset),e.reset_source&&o.add(e.reset_source)}),document.getElementById("val-hazards").textContent=n,document.getElementById("val-sync").textContent=s,document.getElementById("val-total").textContent=activeRDC.length,document.getElementById("val-resets").textContent=o.size,document.getElementById("meta-boundary-count").textContent=`${activeRDC.length} inter-domain path${activeRDC.length!==1?"s":""} analysed`,document.getElementById("cfg-reset-count").textContent=`${o.size} Reset Domain${o.size!==1?"s":""}`,buildInteractionMatrix(Array.from(o),activeRDC),renderPathsTable(activeRDC),r()});function buildInteractionMatrix(t,r){const a=document.getElementById("matrix-wrapper");if(t.length<2){a.innerHTML='<div class="empty-state">Single reset domain design. Zero inter-domain crossings.</div>';return}let n='<table class="matrix-table"><thead><tr><th>Launch \\ Capture</th>';t.forEach(s=>{n+=`<th>${s}</th>`}),n+="</tr></thead><tbody>",t.forEach(s=>{n+=`<tr><td class="row-header">${s}</td>`,t.forEach(o=>{if(s===o)n+='<td class="cell-none">\u2014</td>';else{const e=r.filter(d=>{const h=d.launch_reset||d.reset_source,u=d.capture_reset||d.reset_source;return h===s&&u===o}),c=e.filter(d=>d.type==="rdc_unsync").length,l=e.filter(d=>d.type==="rdc_sync").length;e.length===0?n+='<td class="cell-none">0</td>':c>0?n+=`<td class="cell-bad">\u26A0 ${c} Hazard${c>1?"s":""}</td>`:n+=`<td class="cell-ok">\u2713 ${l} Sync</td>`}}),n+="</tr>"}),n+="</tbody></table>",a.innerHTML=n}i(buildInteractionMatrix,"buildInteractionMatrix");function renderPathsTable(t){const r=document.getElementById("rdc-paths-container");r.innerHTML=t.map((a,n)=>{const s=a.type==="rdc_unsync",o=s?"Add a 2-stage reset synchronizer (async-assert / sync-deassert) in the destination domain. If transferring multi-bit state across resets, use a reset controller with handshake.":"Verified reset synchronizer chain detected. The reset de-assertion is clock-synchronized to the destination domain.",e=a.launch_reset||a.reset_source||"\u2014",c=a.capture_reset||a.reset_source||"\u2014";return`
      <div class="path-row-item">
        <div class="path-row-header" onclick="toggleDetails(${n})">
          <div class="path-left">
            <span class="path-gates-count">${s?"0 gates":"2 sync FF"}</span>
            <span class="path-endpoints">${a.launch_register} \u2192 ${a.capture_register}</span>
          </div>
          <div class="path-right">
            <span class="path-clocks-metric">${e} \u2794 ${c}</span>
            <span class="path-status-badge ${s?"hazard":"safe"}">${s?"HAZARD":"SYNC OK"}</span>
          </div>
        </div>
        <div class="path-details" id="path-details-${n}">
          <div><strong>Diagnostic:</strong> ${a.message}</div>
          <div class="remediation-box">
            <strong>Remediation:</strong> ${o}
          </div>
        </div>
      </div>
    `}).join("")}i(renderPathsTable,"renderPathsTable");function toggleDetails(t){const r=document.getElementById(`path-details-${t}`);r&&r.classList.toggle("open")}i(toggleDetails,"toggleDetails");function exportRDCConstraints(){if(!activeRDC.length){alert("No crossings available to generate constraints.");return}let t=`# ========================================================
`;t+=`# RDC Constraints - Reset Domain Crossing
`,t+=`# Generated by RTL Bench RDC Verification Engine
`,t+=`# ========================================================

`;const r=activeRDC.filter(s=>s.type==="rdc_sync");r.length?(t+=`# Validated Reset Synchronizers
`,r.forEach(s=>{t+=`set_false_path -from [get_cells {${s.launch_register}}] -to [get_cells {${s.capture_register}}]
`})):t+=`# No safe reset synchronized crossings found.
`;const a=new Blob([t],{type:"text/plain"}),n=document.createElement("a");n.href=URL.createObjectURL(a),n.download="rdc_constraints.sdc",n.click()}i(exportRDCConstraints,"exportRDCConstraints");
